version: '3'
services:
  postgres:
    image: postgres:9.4
    env_file:
      - database.env # configure postgres
    volumes:
      - ./test-db-data/:/var/lib/postgresql/data/ # persist data even if container shuts down
    networks:
       - main-network
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    networks:
       - main-network

networks:
  main-network:
